name:                adj2mon
version:             0.1.0.0
github:              "stites/adj2mon"
license:             BSD3
author:              "Sam Stites"
maintainer:          "fnz@fgvgrf.vb (cipher:rot13)"
copyright:           "Copyright: (c) 2018 Sam Stites"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stites/adj2mon#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  adj2mon-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adj2mon
    - hedgehog >= 1.0
    - hedgehog-quickcheck
